### ISSUE TITLE
Add persian number  option

### ISSUE THREAD

**Issue by DanialV** [Ali-Azmoud/persian_datepicker#1]
It would be great if you create a feature for supporting Persian number in date picker because this is a Persian date picker with numbers should be in a Persian format not English.

**Comment by Ali-Azmoud** [comment]
Hi
I think farsi numbers' characters are not really number characters, and everything is going to mess up. I'm going to add a feature which you can change the font type of datepicker parts. numbers, headers, ...

I believe 'Vazir' is a great persian font which supports Farsi numbers as well. 
[here is the link](https://rastikerdar.github.io/vazir-font/), its free

maybe in the future i find a way to work with non-number farsi characters.

**Comment by Ali-Azmoud** [comment]
in the latest version you can use `farsiDigits` to get persian numbers

also you can change font family by `fontFamily` if you have a font supports persian numbers

**Comment by DanialV** [comment]
great thanks so much for the awesome support 
By the way, I couldn't see your source code in your repo, is your library closed source I would like to contribute to it and add some cool feature in future if possible.

**Comment by DanialV** [comment]
I tested new version still something is missing output date which is shown in the text field is still English number I tried onChanged property in order to convert it my self however your library doesn't trigger onChanged property when the date changed.

**Comment by Ali-Azmoud** [comment]
> I tested new version still something is missing output date which is shown in the text field is still English number I tried onChanged property in order to convert it my self however your library doesn't trigger onChanged property when the date changed.

I don't think that gonna work. Farsi numbers are not real number characters, and they don't have number functionalities. it will fail I'm sure.  

also `TextField`'s style is outside the scope of this library. It's inside the scope of your App  

About the source, I forgot to upload it here. I will, tonight or tomorrow

**Comment by Ali-Azmoud** [comment]
You know, I'm going to give it a shot tonight. I'm sure it can be done somehow :)
so I'm going to reopen this issue

**Comment by DanialV** [comment]
thanks, it is awesome now and thanks again for your great support.
