### ISSUE TITLE
سرعت کم

### ISSUE THREAD

**Issue by evangelme** [Ali-Azmoud/persian_datepicker#2]
سلام اول خسته نباشی خیلی عالیه ولی یکم سرعتش کم هست دلیلی چی میتونه باشه؟

**Comment by Ali-Azmoud** [comment]
درود. اگه در حالت دیباگ هستید سرعت پایینه ولی توی نسخه ریلیز اپ، سرعت مناسبه

**Comment by evangelme** [comment]
ممنون مرسی درست می فرمایید فقط جهت ارتقا بنده قبلا react native کار می کردم این component خیلی قابلیت های خوبی داره گفتم اگه به مرور زمان اضافه کنید خیلی عالی میشه ممنون 
https://www.npmjs.com/package/react-native-calendars-persian

**Comment by Ali-Azmoud** [comment]
بله. قابلیت های بسیار خوبی داره اما خب یک دیت پیکر با تقویم فرق میکنه. ماهیت این پلاگین تقویم بودن نیست. ولی میشه برخی قابلیت هاش رو اضافه کرد. ممنون بابت معرفی کامپوننت
