### ISSUE TITLE
The method 'call' was called on null.

### ISSUE THREAD

**Issue by wkhaksar** [Ali-Azmoud/persian_datepicker#3]
Hi, 
An issue I am currently facing with this widget is, when I am tapping on a day to select, a DEBUG CONSOLE exception appears at console as following:

`I/flutter (26259): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
I/flutter (26259): #1      _PersianDatePickerWidgetState._dayBlock.<anonymous closure> 
package:persian_datepicker/persian_datepicker.dart:1080
I/flutter (26259): #2      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:635
I/flutter (26259): #3      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:711
I/flutter (26259): #4      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
I/flutter (26259): #5      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:365
I/flutter (26259): #6      TapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:312
I/flutter (26259): #7      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
I/flutter (26259): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
I/flutter (26259): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
I/flutter (26259): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
I/flutter (26259): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
I/flutter (26259): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
I/flutter (26259): #16     _invoke1  (dart:ui/hooks.dart:250:10)
I/flutter (26259): #17     _dispatchPointerDataPacket  (dart:ui/hooks.dart:159:5)
I/flutter (26259): (elided 3 frames from package dart:async)
I/flutter (26259): Handler: "onTap"
I/flutter (26259): Recognizer:
I/flutter (26259):   TapGestureRecognizer#a72df
I/flutter (26259): `

Here is my widget:
```flutter
import 'package:flutter/material.dart';
import 'package:persian_datepicker/persian_datepicker.dart';

class TestScreen extends StatefulWidget {
  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  final TextEditingController textEditingController = TextEditingController();
  PersianDatePickerWidget persianDatePicker;

  @override
  void initState() {
    super.initState();

    persianDatePicker = PersianDatePicker(
      controller: textEditingController,
      //datetime: '1397/06/09',
      outputFormat: 'YYYY/MM/DD',
    ).init();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          "Sample App",
          style:
              Theme.of(context).textTheme.title.copyWith(color: Colors.white),
        ),
        actions: <Widget>[
          Container(
            child: Image.asset("assets/images/white-logo.png"),
            padding: EdgeInsets.all(8),
          ),
        ],
      ),
      body: Container(
        child: Padding(
            padding: const EdgeInsets.all(8.0), child: persianDatePicker),
      ),
    );
  }
}
```

**Comment by hassanbht** [comment]
سلام خسته نباشی
زمانی که
farsiDigits: true,
می کنم ارور 
The following NoSuchMethodError was thrown while handling a gesture:
I/flutter ( 8392): The method 'call' was called on null.
I/flutter ( 8392): Receiver: null
I/flutter ( 8392): Tried calling: call("۱۳۹۸/۰۶/۰۵", "1398/06/12")
 میده در ضمن 
finishDatetime
مشخص کنم درست میشه ولی من نمی خوام از رنج تاریخ استفاده کنم
ممنون میشم راهنمای بفرمایید

**Comment by mbyervand** [comment]
سلام من هم همین مشکل را دارم

![image](https://user-images.githubusercontent.com/56269494/68075827-919d5200-fdc2-11e9-86a0-75016ffbbbb0.png)

**Comment by Ali-Azmoud** [comment]
درود. متاسفانه به علت مشغله زیاد نتونستم به این پکیج سر بزنم. بزودی نسخه جدید اپلود میکنم و باگی که گفتید هم توش رفع میشه. سپاس

**Comment by master11641** [comment]
سلام این خطا برای من هم هست متاسفانه

**Comment by Ali-Azmoud** [comment]
وقت بخیر. این مشکل در آخرین نسخه رفع شد. سپاس از همگی دوستان
