### ISSUE TITLE
نحوه غیرفعال کردن روزای ماقبل روز فعلی

### ISSUE THREAD

**Issue by sardarmz** [Ali-Azmoud/persian_datepicker#6]
سلام ببخشید دوتاسوال دارم ممنون میشم جواب بدین:

1- چرا موقعی که فارسی میکنیم تقویم رو عددی که تومتغیر ذخیره میکنیم هم فارسی میده نمیشه نمایش برای کاربر اعداد فارسی باشه ولی چیزی که ست میشه تو متغیر با اعداد انگلیسی باشه

2- چطوری میتونم روزای ماقبل روز فعلی رو غیر فعال کنم یا رنگشون عوض کنم که کاربر نتونه انتخاب کنه

**Comment by Ali-Azmoud** [comment]
درود. فکر کنم با قابلیت های اخرین نسخه بشه. اینکه میگم فکر کنم چون خیلی وقته سر نزدم و کد رو یادم رفته. بررسی میکنم خبر میدم. سپاس
