### ISSUE TITLE
سورس کد اصلی برنامه

### ISSUE THREAD

**Issue by alizera** [Ali-Azmoud/persian_datepicker#7]
سلام دوست من
ممنون بخاطر لایبرری فوق‌العاده‌ای که نوشتی
ولی سوال من اینه که خود سورس‌کدش کجاست من می‌خوام کانتریبیوت کنم ولی دیدم تووی "لیب" فقط "مین" هست که اونم عملا اپ تسته.
ممنون.

**Comment by Ali-Azmoud** [comment]
سلام. وقت بخیر. سورس رو امشب قرار میدم .

**Comment by Ali-Azmoud** [comment]
وقت بخیر. سورس کد برنامه حدود 2 هفته پیش قرار داده شد. این ایشو رو میبندم. در صورتی که نیاز بود بازش کنید. سپاس
